//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_kyc
    {
        public int id { get; set; }
        public Nullable<int> registeredid { get; set; }
        public string certificateofincorporation { get; set; }
        public string memorandomofassociation { get; set; }
        public string articlesofassociation { get; set; }
        public string powerofattorneygranted { get; set; }
        public string validbusinesslicense { get; set; }
        public string auditedfinancialstatement { get; set; }
        public string taxclearancecertificate { get; set; }
        public Nullable<System.DateTimeOffset> dateadded { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> approvedby { get; set; }
        public string approvalcomment { get; set; }
        public Nullable<System.DateTimeOffset> dateapproved { get; set; }
    }
}
