//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_subgoodstype
    {
        public int id { get; set; }
        public Nullable<int> goodstypeid { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTimeOffset> dateadded { get; set; }
        public Nullable<int> statusid { get; set; }
    }
}
