//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class powerusyDBCoreEntities : DbContext
    {
        public powerusyDBCoreEntities()
            : base("name=powerusyDBCoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<tbl_AuditLog> tbl_AuditLog { get; set; }
        public virtual DbSet<tbl_Clearing> tbl_Clearing { get; set; }
        public virtual DbSet<tbl_GoodsType> tbl_GoodsType { get; set; }
        public virtual DbSet<tbl_Importation> tbl_Importation { get; set; }
        public virtual DbSet<tbl_ImportationDocument> tbl_ImportationDocument { get; set; }
        public virtual DbSet<tbl_KYC> tbl_KYC { get; set; }
        public virtual DbSet<tbl_Registered> tbl_Registered { get; set; }
        public virtual DbSet<tbl_role> tbl_role { get; set; }
        public virtual DbSet<tbl_serviceType> tbl_serviceType { get; set; }
        public virtual DbSet<tbl_Shipper> tbl_Shipper { get; set; }
        public virtual DbSet<tbl_status> tbl_status { get; set; }
        public virtual DbSet<tbl_SubGoodsType> tbl_SubGoodsType { get; set; }
        public virtual DbSet<tbl_user> tbl_user { get; set; }
    }
}
