//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_attachment
    {
        public int id { get; set; }
        public string fileName { get; set; }
        public string path { get; set; }
        public Nullable<int> status { get; set; }
        public string commnet { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> userid { get; set; }
    }
}
