//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Clearing
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int GoodsId { get; set; }
        public string FinalInvoice { get; set; }
        public string BillOfLading { get; set; }
        public string PackingList { get; set; }
        public string CombinedCertificate { get; set; }
        public string SONCAP { get; set; }
        public Nullable<int> ApprovedById { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string Comment { get; set; }
    }
}
