//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Registered
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Registered()
        {
            this.tbl_KYC = new HashSet<tbl_KYC>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string CompanyName { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public string Description { get; set; }
        public string CompanyLocation { get; set; }
        public string CompanyAddress { get; set; }
        public string CompanyLogo { get; set; }
        public string PostAddress { get; set; }
        public string WorkingDays { get; set; }
        public string WorkingHours { get; set; }
        public string BankName { get; set; }
        public string AccountNumber { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<int> StatusId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<int> tbl_serviceTypeId { get; set; }
        public Nullable<int> tbl_statusId { get; set; }
        public Nullable<int> tbl_userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KYC> tbl_KYC { get; set; }
        public virtual tbl_serviceType tbl_serviceType { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
