//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ImportationDocument
    {
        public int Id { get; set; }
        public int ImportationId { get; set; }
        public string DocumentName { get; set; }
        public string DcoumentPath { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Approvedby { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<int> tbl_ImportationId { get; set; }
        public Nullable<int> tbl_statusId { get; set; }
        public Nullable<int> tbl_userId { get; set; }
    
        public virtual tbl_Importation tbl_Importation { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
