//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_clearing
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public Nullable<int> goodsid { get; set; }
        public string finalinvoice { get; set; }
        public string billoflanding { get; set; }
        public string packinglist { get; set; }
        public string combinedcertificate { get; set; }
        public string soncap { get; set; }
        public string approvedbyid { get; set; }
        public Nullable<System.DateTimeOffset> dateapproved { get; set; }
        public string comment { get; set; }
    }
}
