//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_user()
        {
            this.tbl_ImportationDocument = new HashSet<tbl_ImportationDocument>();
            this.tbl_KYC = new HashSet<tbl_KYC>();
            this.tbl_Registered = new HashSet<tbl_Registered>();
            this.tbl_Shipper = new HashSet<tbl_Shipper>();
        }
    
        public int Id { get; set; }
        public string username { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string PhoneNumber { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> RoleID { get; set; }
        public bool Status { get; set; }
        public string Email { get; set; }
        public Nullable<int> tbl_roleId { get; set; }
        public string Password { get; set; }
        public string AuthCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ImportationDocument> tbl_ImportationDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_KYC> tbl_KYC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Registered> tbl_Registered { get; set; }
        public virtual tbl_role tbl_role { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Shipper> tbl_Shipper { get; set; }
    }
}
