//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_cars_models
    {
        public int ID { get; set; }
        public string CarMake { get; set; }
        public Nullable<int> Year { get; set; }
        public string Model { get; set; }
        public string Category { get; set; }
    }
}
