//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bookmarked
    {
        public long ID { get; set; }
        public Nullable<int> BidID { get; set; }
        public Nullable<int> AgentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> status { get; set; }
    }
}
