//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_shipper
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string companyname { get; set; }
        public string tin { get; set; }
        public string tinpassword { get; set; }
        public string location { get; set; }
        public string phonenumber { get; set; }
        public string statusid { get; set; }
        public Nullable<int> approvedby { get; set; }
        public string comment { get; set; }
        public string description { get; set; }
        public string workingdays { get; set; }
        public string workinghours { get; set; }
        public string bankname { get; set; }
        public string accountnumber { get; set; }
        public Nullable<System.DateTime> dateadded { get; set; }
        public string address { get; set; }
    }
}
