//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Importation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Importation()
        {
            this.tbl_ImportationDocument = new HashSet<tbl_ImportationDocument>();
        }
    
        public int Id { get; set; }
        public int ShippersId { get; set; }
        public int GoodsTypeId { get; set; }
        public int SubGoodTypeId { get; set; }
        public string Comment { get; set; }
        public int ServiceTypeId { get; set; }
        public int Status { get; set; }
        public System.DateTime DateAdded { get; set; }
        public Nullable<int> tbl_GoodsTypeId { get; set; }
        public Nullable<int> tbl_serviceTypeId { get; set; }
        public Nullable<int> tbl_ShipperId { get; set; }
        public Nullable<int> tbl_statusId { get; set; }
        public Nullable<int> tbl_SubGoodsTypeId { get; set; }
    
        public virtual tbl_GoodsType tbl_GoodsType { get; set; }
        public virtual tbl_serviceType tbl_serviceType { get; set; }
        public virtual tbl_Shipper tbl_Shipper { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_SubGoodsType tbl_SubGoodsType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ImportationDocument> tbl_ImportationDocument { get; set; }
    }
}
