//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_registered
    {
        public int id { get; set; }
        public Nullable<int> userid { get; set; }
        public string companyname { get; set; }
        public Nullable<int> serviceid { get; set; }
        public string description { get; set; }
        public string companylocation { get; set; }
        public string companyaddress { get; set; }
        public string companylogo { get; set; }
        public string postaddress { get; set; }
        public string workingdays { get; set; }
        public string workinghours { get; set; }
        public string bankname { get; set; }
        public string accountnumber { get; set; }
        public Nullable<System.DateTimeOffset> dateadded { get; set; }
        public Nullable<int> statusid { get; set; }
        public Nullable<int> approvedby { get; set; }
        public Nullable<System.DateTimeOffset> dateapproved { get; set; }
        public string approvalcomment { get; set; }
    }
}
