//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_KYC
    {
        public int Id { get; set; }
        public int RegisteredId { get; set; }
        public string CertificateOfIncorporation { get; set; }
        public string MemorandomOfAssociation { get; set; }
        public string ArticlesOfAssociation { get; set; }
        public string PowerOfAttorneyGranted { get; set; }
        public string ValidBusinessLicense { get; set; }
        public string AuditedFinancialStatement { get; set; }
        public string TaxClearanceCertificate { get; set; }
        public System.DateTime DateAdded { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> Approvedby { get; set; }
        public string ApprovalComment { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public Nullable<int> tbl_RegisteredId { get; set; }
        public Nullable<int> tbl_statusId { get; set; }
        public Nullable<int> tbl_userId { get; set; }
    
        public virtual tbl_Registered tbl_Registered { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
