//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_bidding_bookmark
    {
        public int bidding_id { get; set; }
        public int bookmarked_by_id { get; set; }
        public int bid_owner_id { get; set; }
    }
}
