//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_sea_ports
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string city { get; set; }
        public string country { get; set; }
        public string alias { get; set; }
        public string regions { get; set; }
        public string coordinates { get; set; }
        public string province { get; set; }
        public string timezone { get; set; }
        public string unlocs { get; set; }
        public string code { get; set; }
    }
}
