//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerusyData.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Shipper
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Shipper()
        {
            this.tbl_Importation = new HashSet<tbl_Importation>();
        }
    
        public int Id { get; set; }
        public int UserId { get; set; }
        public string CompanyName { get; set; }
        public string TIN { get; set; }
        public string TINPassword { get; set; }
        public string Location { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailAddress { get; set; }
        public int StatusId { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> DateApproved { get; set; }
        public string Comment { get; set; }
        public Nullable<int> tbl_statusId { get; set; }
        public Nullable<int> tbl_userId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Importation> tbl_Importation { get; set; }
        public virtual tbl_status tbl_status { get; set; }
        public virtual tbl_user tbl_user { get; set; }
    }
}
